In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("11-iris.csv")

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
#id kolonu silinebilir
# sprecies kolonu ise encode edilecek
df.drop("Id", inplace=True, axis=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
#array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object) => 0, 1, 2 vb.

In [20]:
from sklearn.preprocessing import LabelEncoder

lbel = LabelEncoder()
df["Species"] = lbel.fit_transform(df["Species"])

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [23]:
df.Species.unique()

array([0, 1, 2])

# Modeller

In [29]:
from sklearn.model_selection import train_test_split

y = df["Species"]
X =df.drop("Species", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.preprocessing import StandardScaler

scal = StandardScaler()
X_train_scale =  scal.fit_transform(X_train)
X_test_scale = scal.transform(X_test)

from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

gaus = GaussianNB()

#Gaus
gaus.fit(X_train_scale, y_train)
y_gaus_pred=gaus.predict(X_test_scale)


from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Gauss: \n")
print(accuracy_score(y_test, y_gaus_pred))
print(confusion_matrix(y_test, y_gaus_pred))
print(classification_report(y_test, y_gaus_pred))


#Gaussion -> veri tipi: Sürekli değerler
#Bernoulli -> veri tipi: 0/1 ikili değer
#Multinominal -> veri tipi: pozitif tam sayılar

Gauss: 

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV

log_reg = LogisticRegression()

log_reg.fit(X_train_scale, y_train)
log_reg_pred = log_reg.predict(X_test_scale)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Logistic Regression: \n")
print(accuracy_score(y_test, log_reg_pred))
print(confusion_matrix(y_test, log_reg_pred))
print(classification_report(y_test, log_reg_pred))

Logistic Regression: 

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

